name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Auto Detect Directory and Build APK
        run: |
          FLUTTER_ROOT=$(dirname $(find . -name "pubspec.yaml" | head -n 1))
          echo "Found project at: $FLUTTER_ROOT"
          cd "$FLUTTER_ROOT"
          flutter pub get
          flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: '**/build/app/outputs/flutter-apk/app-release.apk'
